import { db, Timestamp } from "../firebase/firestore.js";
import { ApiError } from "../utils/errors.js";
import { ORDER_FLOW, isOrderStatus, isTerminalOrderStatus, isValidNextOrderStatus } from "./orderLifecycle.js";
export { ORDER_FLOW } from "./orderLifecycle.js";
export type { OrderStatus } from "./orderLifecycle.js";

export async function listOrders(filters:{status?:string;paymentStatus?:string;from?:string;to?:string}) { let q:any=db.collection("orders").orderBy("createdAt","desc");if(filters.status)q=q.where("status","==",filters.status);if(filters.paymentStatus)q=q.where("paymentStatus","==",filters.paymentStatus);if(filters.from){const d=new Date(filters.from);if(Number.isNaN(d.getTime()))throw new ApiError(400,"INVALID_DATE","Invalid from date");q=q.where("createdAt",">=",Timestamp.fromDate(d));}if(filters.to){const d=new Date(filters.to);if(Number.isNaN(d.getTime()))throw new ApiError(400,"INVALID_DATE","Invalid to date");q=q.where("createdAt","<=",Timestamp.fromDate(d));}const s=await q.limit(100).get();return s.docs.map((d:any)=>({id:d.id,...d.data()})); }
export async function transitionOrder(id:string,next:import("./orderLifecycle.js").OrderStatus){if(!isOrderStatus(next))throw new ApiError(400,"INVALID_STATUS","Invalid order status");const ref=db.collection("orders").doc(id);return db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw new ApiError(404,"NOT_FOUND","Order not found");const data=s.data()!,cur=String(data.status);if(isTerminalOrderStatus(cur))throw new ApiError(409,"TERMINAL_ORDER","Terminal orders cannot be changed");if(!isOrderStatus(cur))throw new ApiError(409,"INVALID_CURRENT_STATUS","Order has an invalid lifecycle state");if(!isValidNextOrderStatus(cur,next))throw new ApiError(409,"INVALID_TRANSITION",`Invalid transition ${cur} -> ${next}`);const now=Timestamp.now(),history=Array.isArray(data.statusHistory)?data.statusHistory:[];tx.update(ref,{status:next,updatedAt:now,statusHistory:[...history,{from:cur,to:next,at:now}]});return{id,status:next};});}
export async function stats(){const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate());const [orders,low,returns]=await Promise.all([db.collection("orders").where("createdAt",">=",Timestamp.fromDate(start)).get(),db.collection("products").where("isActive","==",true).get(),db.collection("return_requests").where("status","==","PENDING").get()]);const lowCount=low.docs.filter(d=>{const x=d.data(),threshold=Number(x.lowStockThreshold??5),stock=Number(x.stockQuantity??0);if(Array.isArray(x.variants)&&x.variants.length)return x.variants.some((v:{stockQuantity?:number;lowStockThreshold?:number})=>Number(v.stockQuantity??0)<=Number(v.lowStockThreshold??threshold));return stock<=threshold;}).length;const revenue=orders.docs.reduce((n,d)=>n+(d.data().paymentStatus==="PAID"?Number(d.data().total):0),0);return{todayOrders:orders.size,revenue,lowStockAlerts:lowCount,pendingReturns:returns.size};}
