import { Router } from "express";
import { z } from "zod";
import { authenticate, requireAdmin, type AuthenticatedRequest } from "../middleware/authenticate.js";
import { requireMfa } from "../middleware/requireMfa.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { listDeliveryZones, getDeliveryZoneByPostalCode, createDeliveryZone, updateDeliveryZone, deleteDeliveryZone } from "../services/deliveryZone.service.js";
import { listCoupons, createCoupon, updateCoupon, deactivateCoupon, validateCoupon } from "../services/coupon.service.js";
import { processCheckout, cancelOrder } from "../controllers/checkout.controller.js";
import { checkoutRateLimiter, writeRateLimiter } from "../middleware/rateLimiter.js";
const router=Router();
const zoneSchema=z.object({name:z.string().min(1).max(100),postalCodes:z.array(z.string().regex(/^\d{4,10}$/)).min(1),baseCharge:z.number().nonnegative(),minimumOrderValue:z.number().nonnegative(),freeDeliveryThreshold:z.number().nonnegative().optional(),isActive:z.boolean().default(true)});
const couponSchema=z.object({code:z.string().min(2).max(50),type:z.enum(["PERCENTAGE","FIXED"]),value:z.number().positive(),minOrderValue:z.number().nonnegative().default(0),maxDiscount:z.number().positive().optional(),usageLimit:z.number().int().positive().optional(),perUserLimit:z.number().int().positive().optional(),categoryIds:z.array(z.string()).optional(),startsAt:z.string().datetime().optional(),expiresAt:z.string().datetime().optional(),isActive:z.boolean().default(true)}).superRefine((v,c)=>{if(v.type==="PERCENTAGE"&&v.value>100)c.addIssue({code:z.ZodIssueCode.custom,path:["value"],message:"Percentage cannot exceed 100"});if(v.expiresAt&&v.startsAt&&new Date(v.expiresAt)<=new Date(v.startsAt))c.addIssue({code:z.ZodIssueCode.custom,path:["expiresAt"],message:"Expiry must be after start"});});
router.get("/delivery-zones/lookup",asyncHandler(async(req,res)=>{const postalCode=String(req.query.postalCode??"").trim();if(!/^\d{4,10}$/.test(postalCode))return res.status(400).json({message:"Valid postalCode is required"});const zone=await getDeliveryZoneByPostalCode(postalCode);if(!zone)return res.status(404).json({message:"Delivery unavailable"});res.json({success:true,zone});}));
router.get("/delivery-zones",authenticate,requireAdmin,asyncHandler(async(_req,res)=>res.json({success:true,zones:await listDeliveryZones()})));
router.post("/delivery-zones",authenticate,requireAdmin,requireMfa,writeRateLimiter,asyncHandler(async(req,res)=>{const v=zoneSchema.parse(req.body);res.status(201).json({success:true,zone:await createDeliveryZone(v)});}));
router.patch("/delivery-zones/:id",authenticate,requireAdmin,requireMfa,writeRateLimiter,asyncHandler(async(req,res)=>{const v=zoneSchema.partial().parse(req.body);res.json({success:true,zone:await updateDeliveryZone(req.params.id,v)});}));
router.delete("/delivery-zones/:id",authenticate,requireAdmin,requireMfa,writeRateLimiter,asyncHandler(async(req,res)=>{await deleteDeliveryZone(req.params.id);res.json({success:true});}));
router.post("/coupons/validate",authenticate,asyncHandler(async(req,res)=>{const request=req as AuthenticatedRequest;const code=z.string().min(2).parse(req.body.code);const subtotal=z.number().nonnegative().parse(req.body.subtotal);const categories=z.array(z.string()).optional().parse(req.body.categoryIds)??[];res.json({success:true,...await validateCoupon(code,subtotal,request.user!.uid,categories)});}));
router.get("/coupons",authenticate,requireAdmin,asyncHandler(async(_req,res)=>res.json({success:true,coupons:await listCoupons()})));
router.post("/coupons",authenticate,requireAdmin,requireMfa,writeRateLimiter,asyncHandler(async(req,res)=>{const v=couponSchema.parse(req.body);const data={...v,startsAt:v.startsAt?new Date(v.startsAt):undefined,expiresAt:v.expiresAt?new Date(v.expiresAt):undefined};res.status(201).json({success:true,coupon:await createCoupon(data as never)});}));
router.patch("/coupons/:id",authenticate,requireAdmin,requireMfa,writeRateLimiter,asyncHandler(async(req,res)=>{const v=couponSchema.partial().parse(req.body);await updateCoupon(req.params.id,v as never);res.json({success:true});}));
router.delete("/coupons/:id",authenticate,requireAdmin,requireMfa,writeRateLimiter,asyncHandler(async(req,res)=>{await deactivateCoupon(req.params.id);res.json({success:true});}));
router.post("/checkout/process",authenticate,checkoutRateLimiter,asyncHandler(processCheckout));
router.post("/orders/:orderId/cancel",authenticate,writeRateLimiter,asyncHandler(cancelOrder));
export default router;
