import { Router } from "express";
import uploadRoutes from "./upload.routes.js";
import authRoutes from "./auth.routes.js";
import productRoutes from "./product.routes.js";
import commerceRoutes from "./commerce.routes.js";
import orderRoutes from "./order.routes.js";
import adminOrderRoutes from "./adminOrder.routes.js";
import engagementRoutes from "./engagement.routes.js";
export const apiRouter=Router();
apiRouter.use("/auth",authRoutes);
apiRouter.use("/products",productRoutes);
apiRouter.use("/uploads",uploadRoutes);
apiRouter.use("/orders",orderRoutes);
apiRouter.use("/admin",adminOrderRoutes);
apiRouter.use("/",engagementRoutes);
apiRouter.use("/",commerceRoutes);
export default apiRouter;
