import { Link } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { getAuth, signOut } from "firebase/auth";

const cards=[
  ["📦","My Orders","View purchases and track deliveries.","/account/orders"],
  ["📍","Addresses","Manage saved delivery addresses.","/account/addresses"],
  ["♡","Wishlist","View products you saved for later.","/wishlist"],
  ["💬","Support","Get help with orders and products.","/messages"],
] as const;
export default function Account(){const{user,loading}=useAuth();if(loading)return <main className="mx-auto max-w-5xl px-4 py-10"><div className="animate-pulse space-y-4"><div className="h-40 rounded-3xl bg-slate-200"/><div className="grid gap-4 sm:grid-cols-2"><div className="h-28 rounded-3xl bg-slate-200"/><div className="h-28 rounded-3xl bg-slate-200"/></div></div></main>;if(!user)return <main className="mx-auto max-w-3xl px-4 py-14"><div className="rounded-[2rem] border bg-white p-10 text-center shadow-sm"><div className="text-6xl">👤</div><h1 className="mt-4 text-3xl font-black">Welcome to RamjanStore</h1><p className="mx-auto mt-2 max-w-md text-slate-500">Sign in to manage your orders, addresses, wishlist and support requests.</p><Link to="/login" className="mt-6 inline-flex rounded-2xl bg-[#00875A] px-6 py-3 font-black text-white">Sign In</Link></div></main>;
const name=user.displayName||user.email?.split("@")[0]||"Customer";return <main className="mx-auto max-w-5xl px-4 py-8 lg:px-6"><section className="overflow-hidden rounded-[2rem] bg-[#172B4D] p-6 text-white shadow-xl sm:p-8"><div className="flex flex-wrap items-center justify-between gap-5"><div className="flex items-center gap-4"><div className="grid h-16 w-16 place-items-center overflow-hidden rounded-2xl bg-white/15 text-2xl font-black">{user.photoURL?<img src={user.photoURL} alt="" className="h-full w-full object-cover"/>:name.charAt(0).toUpperCase()}</div><div><p className="text-xs font-bold uppercase tracking-widest text-white/60">My Account</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">Hello, {name}</h1><p className="mt-1 text-sm text-white/70">{user.email||"Signed in customer"}</p></div></div><button onClick={()=>void signOut(getAuth())} className="rounded-xl border border-white/20 px-4 py-2 text-sm font-bold hover:bg-white/10">Sign out</button></div></section><section className="mt-6 grid gap-4 sm:grid-cols-2">{cards.map(([icon,title,desc,to])=><Link key={to} to={to} className="group rounded-3xl border bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between"><span className="text-3xl">{icon}</span><span className="text-slate-300 transition group-hover:translate-x-1 group-hover:text-[#00875A]">→</span></div><h2 className="mt-5 font-black">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{desc}</p></Link>)}</section><section className="mt-6 rounded-3xl border bg-white p-6 shadow-sm"><h2 className="font-black">Account information</h2><div className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Name</p><p className="mt-1 font-semibold">{user.displayName||"Not provided"}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Email</p><p className="mt-1 font-semibold">{user.email||"Not provided"}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Phone</p><p className="mt-1 font-semibold">{user.phoneNumber||"Not provided"}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Sign-in provider</p><p className="mt-1 font-semibold">{user.providerData[0]?.providerId?.replace(".com","")||"Firebase"}</p></div></div><p className="mt-5 rounded-2xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">Profile editing will be enabled when a customer profile update endpoint is available in the backend. Your Firebase account information above is read directly from the authenticated session.</p></section></main>}
