import { Link, useNavigate } from "react-router-dom";
import { useCartStore } from "../lib/cartStore";

export default function Cart() {
  const navigate = useNavigate();
  const { items, setQuantity, removeItem, subtotal } = useCartStore();
  const total = subtotal();
  if (!items.length) return <main className="mx-auto max-w-5xl px-4 py-16 text-center lg:px-6"><div className="rounded-3xl border bg-white p-10 shadow-sm"><div className="text-6xl">🛒</div><h1 className="mt-5 text-3xl font-black">Your cart is empty</h1><p className="mt-2 text-slate-500">Add products from RamjanStore and they will appear here.</p><Link to="/products" className="mt-6 inline-flex rounded-2xl bg-[#00875A] px-6 py-3 font-bold text-white">Start Shopping →</Link></div></main>;
  return <main className="mx-auto max-w-6xl px-4 py-8 lg:px-6"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-[#00875A]">RamjanStore</p><h1 className="mt-2 text-3xl font-black">Your Cart</h1><p className="mt-1 text-sm text-slate-500">{items.reduce((n,i)=>n+i.quantity,0)} item(s) ready for checkout</p></div><Link to="/products" className="text-sm font-bold text-[#00875A]">Continue shopping</Link></div><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="space-y-3">{items.map(item => <article key={`${item.productId}:${item.variantId ?? "default"}`} className="flex gap-4 rounded-3xl border bg-white p-4 shadow-sm"><div className="h-24 w-24 shrink-0 overflow-hidden rounded-2xl bg-slate-100">{item.imageUrl && <img src={item.imageUrl} alt={item.name} className="h-full w-full object-cover"/>}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><div><h2 className="font-black">{item.name}</h2><p className="mt-1 text-sm text-slate-500">₹{item.unitPrice.toLocaleString("en-IN")} each</p></div><button onClick={()=>removeItem(item.productId,item.variantId)} className="text-sm font-bold text-red-600">Remove</button></div><div className="mt-4 flex items-center gap-3"><div className="flex items-center rounded-xl border"><button aria-label={`Decrease ${item.name}`} onClick={()=>setQuantity(item.productId,item.quantity-1,item.variantId)} className="px-3 py-1.5 font-bold">−</button><span className="min-w-9 text-center text-sm font-bold">{item.quantity}</span><button aria-label={`Increase ${item.name}`} onClick={()=>setQuantity(item.productId,item.quantity+1,item.variantId)} className="px-3 py-1.5 font-bold">+</button></div><strong>₹{(item.unitPrice*item.quantity).toLocaleString("en-IN")}</strong></div></div></article>)}</section><aside className="h-fit rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Order Summary</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">Subtotal</span><strong>₹{total.toLocaleString("en-IN")}</strong></div><div className="flex justify-between"><span className="text-slate-500">Delivery</span><span className="font-semibold">Calculated at checkout</span></div></div><div className="my-5 border-t"/><div className="flex justify-between text-lg"><span className="font-bold">Total</span><strong>₹{total.toLocaleString("en-IN")}</strong></div><button onClick={()=>navigate("/checkout")} className="mt-6 w-full rounded-2xl bg-[#00875A] px-5 py-3.5 font-black text-white shadow-lg shadow-[#00875A]/20">Proceed to Checkout →</button><p className="mt-3 text-center text-xs text-slate-500">Secure checkout • Multiple payment options</p></aside></div></main>;
}
