import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import type { Product } from "@ramjanstore/types";
import { ProductEngagement } from "../components/product/EngagementWidgets";
import { useCartStore } from "../lib/cartStore";

export default function ProductDetail() {
  const { slug } = useParams(); const navigate = useNavigate(); const addItem = useCartStore(s => s.addItem);
  const [p,setP] = useState<Product|null>(null); const [loading,setLoading] = useState(true); const [error,setError] = useState(""); const [image,setImage] = useState(0); const [quantity,setQuantity] = useState(1);
  useEffect(() => { setLoading(true); setError(""); void fetch(`${import.meta.env.VITE_API_URL??"http://localhost:4000/api/v1"}/products/${encodeURIComponent(slug??"")}`).then(async r => { if(!r.ok) throw new Error("Product unavailable"); return r.json(); }).then(x=>setP(x.data??null)).catch(()=>setError("Unable to load this product right now.")).finally(()=>setLoading(false)); },[slug]);
  if(loading) return <main className="mx-auto max-w-6xl px-4 py-8"><div className="grid animate-pulse gap-8 md:grid-cols-2"><div className="aspect-square rounded-3xl bg-slate-200"/><div className="space-y-5"><div className="h-4 w-24 rounded bg-slate-200"/><div className="h-10 w-3/4 rounded bg-slate-200"/><div className="h-8 w-32 rounded bg-slate-200"/><div className="h-24 rounded bg-slate-200"/></div></div></main>;
  if(error || !p) return <main className="mx-auto max-w-5xl px-4 py-16 text-center"><h1 className="text-3xl font-black">Product not found</h1><p className="mt-2 text-slate-500">{error || "This product may have been removed."}</p><Link className="mt-6 inline-flex font-bold text-[#00875A]" to="/products">← Back to products</Link></main>;
  const images = p.images?.length ? p.images : []; const active = images[image]?.url;
  function add(){ addItem({productId:p.id,name:p.name,unitPrice:p.price,quantity,imageUrl:active}); }
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:py-10 lg:px-6"><div className="mb-5 text-sm text-slate-500"><Link to="/products" className="hover:text-[#00875A]">Products</Link> <span className="mx-2">/</span> {p.category}</div><div className="grid gap-8 md:grid-cols-[minmax(0,1.05fr)_minmax(320px,.95fr)]"><section><div className="aspect-square overflow-hidden rounded-[2rem] border bg-slate-100 shadow-sm">{active ? <img src={active} alt={p.name} className="h-full w-full object-cover"/> : <div className="grid h-full place-items-center text-7xl">🛍️</div>}</div>{images.length>1&&<div className="mt-3 grid grid-cols-5 gap-2">{images.slice(0,5).map((img,i)=><button key={img.url} onClick={()=>setImage(i)} className={`aspect-square overflow-hidden rounded-xl border-2 ${i===image?"border-[#00875A]":"border-transparent"}`}><img src={img.url} alt={`${p.name} ${i+1}`} className="h-full w-full object-cover"/></button>)}</div>}</section><section><p className="text-xs font-bold uppercase tracking-widest text-[#00875A]">{p.category}</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">{p.name}</h1><div className="mt-4 flex items-center gap-3"><span className="text-3xl font-black">₹{p.price.toLocaleString("en-IN")}</span>{p.stock !== undefined && <span className={`rounded-full px-3 py-1 text-xs font-bold ${p.stock>0?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{p.stock>0?`${p.stock} in stock`:"Out of stock"}</span>}</div><p className="mt-5 leading-7 text-slate-600">{p.description}</p><div className="mt-6 rounded-2xl border bg-white p-4"><div className="flex items-center justify-between"><span className="font-bold">Quantity</span><div className="flex items-center rounded-xl border"><button onClick={()=>setQuantity(Math.max(1,quantity-1))} className="px-4 py-2 font-bold">−</button><span className="min-w-10 text-center font-bold">{quantity}</span><button onClick={()=>setQuantity(quantity+1)} className="px-4 py-2 font-bold">+</button></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><button disabled={p.stock===0} onClick={add} className="rounded-2xl border-2 border-[#00875A] px-5 py-3.5 font-black text-[#00875A] disabled:cursor-not-allowed disabled:opacity-40">Add to Cart</button><button disabled={p.stock===0} onClick={()=>{add();navigate("/cart")}} className="rounded-2xl bg-[#00875A] px-5 py-3.5 font-black text-white shadow-lg shadow-[#00875A]/20 disabled:cursor-not-allowed disabled:opacity-40">Buy Now →</button></div></div><div className="mt-5"><ProductEngagement productId={p.id} initialLikes={p.engagement?.likeCount??0}/></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4 text-center text-xs font-bold">🚚 Fast Delivery</div><div className="rounded-2xl bg-slate-50 p-4 text-center text-xs font-bold">🔒 Secure Checkout</div><div className="rounded-2xl bg-slate-50 p-4 text-center text-xs font-bold">↩️ Easy Returns</div></div></section></div></main>;
}
