import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import type { Product } from "@ramjanstore/types";
import { engagementApi } from "../services/engagementApi";
import { useCartStore } from "../lib/cartStore";
import { useAuth } from "../auth/AuthContext";

export default function Wishlist() {
  const { user, loading: authLoading } = useAuth();
  const [items, setItems] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [removing, setRemoving] = useState<string | null>(null);
  const add = useCartStore(s => s.addItem);
  const refresh = async () => { setLoading(true); setError(""); try { const r = await engagementApi.wishlistItems(); setItems(r.data); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load wishlist"); } finally { setLoading(false); } };
  useEffect(() => { if (!authLoading && user) void refresh(); else if (!authLoading) setLoading(false); }, [user, authLoading]);
  const remove = async (id: string) => { setRemoving(id); setError(""); try { await engagementApi.wishlist(id); setItems(current => current.filter(p => p.id !== id)); } catch (e) { setError(e instanceof Error ? e.message : "Could not remove item"); } finally { setRemoving(null); } };
  if (authLoading) return <main className="mx-auto max-w-6xl p-4 sm:p-8"><div className="animate-pulse h-48 rounded-3xl bg-slate-200"/></main>;
  if (!user) return <main className="mx-auto max-w-4xl p-4 sm:p-8"><div className="rounded-3xl border bg-white p-12 text-center"><div className="text-5xl">♡</div><h1 className="mt-3 text-2xl font-black">Sign in to view your wishlist</h1><p className="mt-2 text-slate-500">Save products and access them from any device.</p><Link to="/login" className="mt-5 inline-flex rounded-xl bg-[#00875A] px-5 py-3 font-black text-white">Sign In</Link></div></main>;
  return <main className="mx-auto max-w-6xl p-4 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><Link to="/account" className="text-sm font-bold text-[#00875A]">← Account</Link><h1 className="mt-2 text-3xl font-black">Wishlist</h1><p className="mt-1 text-sm text-slate-500">{loading ? "Loading saved products…" : `${items.length} saved product${items.length === 1 ? "" : "s"}`}</p></div><Link to="/products" className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">Continue shopping</Link></div>{error&&<div className="mt-5 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}{loading?<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map(i=><div key={i} className="animate-pulse rounded-3xl border bg-white p-3"><div className="aspect-square rounded-2xl bg-slate-200"/><div className="mt-4 h-4 w-2/3 rounded bg-slate-200"/><div className="mt-3 h-8 rounded bg-slate-200"/></div>)}</div>:items.length?<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{items.map(p=>{const image=p.images?.[0]?.secureUrl??p.images?.[0]?.url??"";const inStock=(p.stockQuantity??0)>0;return <article key={p.id} className="group overflow-hidden rounded-3xl border bg-white shadow-sm"><Link to={`/product/${p.slug}`}><div className="aspect-square overflow-hidden bg-slate-100">{image?<img src={image} alt={p.name} className="h-full w-full object-cover transition group-hover:scale-105"/>:<div className="grid h-full place-items-center text-5xl">🛍️</div>}</div></Link><div className="p-4"><Link to={`/product/${p.slug}`} className="line-clamp-2 font-black hover:text-[#00875A]">{p.name}</Link><p className="mt-2 text-lg font-black">₹{p.price.toLocaleString("en-IN")}</p><p className={`mt-1 text-xs font-bold ${inStock?"text-emerald-700":"text-red-600"}`}>{inStock?"In stock":"Out of stock"}</p><div className="mt-4 grid grid-cols-2 gap-2"><button disabled={!inStock} onClick={()=>add({productId:p.id,name:p.name,unitPrice:p.price,quantity:1,imageUrl:image||undefined})} className="rounded-xl bg-[#00875A] px-3 py-2 text-xs font-black text-white disabled:cursor-not-allowed disabled:opacity-40">Add to cart</button><button disabled={removing===p.id} onClick={()=>void remove(p.id)} className="rounded-xl border px-3 py-2 text-xs font-black disabled:opacity-50">{removing===p.id?"Removing…":"Remove"}</button></div></div></article>})}</div>:<div className="mt-8 rounded-3xl border bg-white p-12 text-center"><div className="text-6xl">♡</div><h2 className="mt-3 text-2xl font-black">Your wishlist is empty</h2><p className="mt-2 text-slate-500">Save products you love and come back to them later.</p><Link to="/products" className="mt-5 inline-flex rounded-xl bg-[#00875A] px-5 py-3 font-black text-white">Browse Products</Link></div>}</main>;
}
